Top secret:
The year is 2019. Donald Trump is about to withdraw from the Paris
climate Agreement contending that it will "undermine" the U.S. economy,
and put the U.S. "at a permanent disadvantage".
To gain support for his proposal, his administration has developed a
series of distorted graphs to try and sway public opinion. These will
go live next Wednesday (coincidentally, at the same time your
assignment is due). We have someone on the inside that can switch one
of the graphs... if only someone had the ability to produce the perfect
image, thereby saving our planet.
This is where you, come in.
Your mission*, If you choose to accept it, is to find and use publicly
available data and produce an image so potent that it will be burnt
onto the retinas of anyone that sees it. It might simply convey
historical changes in climate accurately, and in a way that is easy to
digest and appealing. However, it might also contain other forms of
information, key events or even other types of data that might derail
the administration’s argument entirely. But avoid political slander.
*You can also make a graph about another global health/social issue if you prefer. The global
covid dataset in the Week 2 folder is a place to start if you don’t have time to find other publicly
available data; If you choose it, do something other than plotting changing case number over
time.

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
df = pd.read_csv("GLobalCovidData.csv")
df.head(20)

,iso_code,continent,location,date,total_cases,new_cases,new_cases_smoothed,total_deaths,new_deaths,new_deaths_smoothed,...,gdp_per_capita,extreme_poverty,cardiovasc_death_rate,diabetes_prevalence,female_smokers,male_smokers,handwashing_facilities,hospital_beds_per_thousand,life_expectancy,human_development_index
0,AFG,Asia,Afghanistan,2/24/20,1.0,1.0,NaN,NaN,NaN,NaN,...,1803.987,NaN,597.029,9.59,NaN,NaN,37.746,0.5,64.83,0.511
1,AFG,Asia,Afghanistan,2/25/20,1.0,0.0,NaN,NaN,NaN,NaN,...,1803.987,NaN,597.029,9.59,NaN,NaN,37.746,0.5,64.83,0.511
2,AFG,Asia,Afghanistan,2/26/20,1.0,0.0,NaN,NaN,NaN,NaN,...,1803.987,NaN,597.029,9.59,NaN,NaN,37.746,0.5,64.83,0.511
3,AFG,Asia,Afghanistan,2/27/20,1.0,0.0,NaN,NaN,NaN,NaN,...,1803.987,NaN,597.029,9.59,NaN,NaN,37.746,0.5,64.83,0.511
4,AFG,Asia,Afghanistan,2/28/20,1.0,0.0,NaN,NaN,NaN,NaN,...,1803.987,NaN,597.029,9.59,NaN,NaN,37.746,0.5,64.83,0.511
5,AFG,Asia,Afghanistan,2/29/20,1.0,0.0,0.143,NaN,NaN,0.0,...,1803.987,NaN,597.029,9.59,NaN,NaN,37.746,0.5,64.83,0.511
6,AFG,Asia,Afghanistan,3/1/20,1.0,0.0,0.143,NaN,NaN,0.0,...,1803.987,NaN,597.029,9.59,NaN,NaN,37.746,0.5,64.83,0.511
7,AFG,Asia,Afghanistan,3/2/20,1.0,0.0,0.000,NaN,NaN,0.0,...,1803.987,NaN,597.029,9.59,NaN,NaN,37.746,0.5,64.83,0.511
8,AFG,Asia,Afghanistan,3/3/20,2.0,1.0,0.143,NaN,NaN,0.0,...,1803.987,NaN,597.029,9.59,NaN,NaN,37.746,0.5,64.83,0.511
9,AFG,Asia,Afghanistan,3/4/20,4.0,2.0,0.429,NaN,NaN,0.0,...,1803.987,NaN,597.029,9.59,NaN,NaN,37.746,0.5,64.83,0.511
10,AFG,Asia,Afghanistan,3/5/20,4.0,0.0,0.429,NaN,NaN,0.0,...,1803.987,NaN,597.029,9.59,NaN,NaN,37.746,0.5,64.83,0.511
11,AFG,Asia,Afghanistan,3/6/20,4.0,0.0,0.429,NaN,NaN,0.0,...,1803.987,NaN,597.029,9.59,NaN,NaN,37.746,0.5,64.83,0.511
12,AFG,Asia,Afghanistan,3/7/20,4.0,0.0,0.429,NaN,NaN,0.0,...,1803.987,NaN,597.029,9.59,NaN,NaN,37.746,0.5,64.83,0.511
13,AFG,Asia,Afghanistan,3/8/20,5.0,1.0,0.571,NaN,NaN,0.0,...,1803.987,NaN,597.029,9.59,NaN,NaN,37.746,0.5,64.83,0.511
14,AFG,Asia,Afghanistan,3/9/20,7.0,2.0,0.857,NaN,NaN,0.0,...,1803.987,NaN,597.029,9.59,NaN,NaN,37.746,0.5,64.83,0.511
15,AFG,Asia,Afghanistan,3/10/20,8.0,1.0,0.857,NaN,NaN,0.0,...,1803.987,NaN,597.029,9.59,NaN,NaN,37.746,0.5,64.83,0.511
16,AFG,Asia,Afghanistan,3/11/20,11.0,3.0,1.000,NaN,NaN,0.0,...,1803.987,NaN,597.029,9.59,NaN,NaN,37.746,0.5,64.83,0.511
17,AFG,Asia,Afghanistan,3/12/20,12.0,1.0,1.143,NaN,NaN,0.0,...,1803.987,NaN,597.029,9.59,NaN,NaN,37.746,0.5,64.83,0.511
18,AFG,Asia,Afghanistan,3/13/20,13.0,1.0,1.286,NaN,NaN,0.0,...,1803.987,NaN,597.029,9.59,NaN,NaN,37.746,0.5,64.83,0.511
19,AFG,Asia,Afghanistan,3/14/20,15.0,2.0,1.571,NaN,NaN,0.0,...,1803.987,NaN,597.029,9.59,NaN,NaN,37.746,0.5,64.83,0.511